[IdRetencionISLR] nvarchar(6) NOT NULL
, [Numero] nvarchar(100) NULL
, [CedulaRif] nvarchar(10) NULL
, [NombreRazonSocial] nvarchar(100) NULL
, [Periodo] nvarchar(100) NULL
, [Direccion] nvarchar(150) NULL
, [Fecha] datetime NULL
, [MontoDocumento] float NULL
, [BaseImponible] float NULL
, [PorcentajeRetencion] float NULL
, [ImpuestoRetenido] float NULL
, [NumeroFactura] nvarchar(100) NULL
, [FechaFactura] datetime NULL
, [Sustraendo] float NULL
, [Control] nvarchar(100) NULL