[Id] nvarchar(20) NOT NULL
, [NumeroDeOperacion] int NULL
, [CedulaRif] nvarchar(10) NULL
, [NombreRazonSocial] nvarchar(150) NULL
, [PeriodoImpositivo] nvarchar(6) NULL
, [FechaDocumento] datetime NULL
, [TipoOperacion] nvarchar(1) NULL
, [TipoDocumento] nvarchar(2) NULL
, [RifAgenteRetencion] nvarchar(10) NULL
, [NumeroDocumento] nvarchar(20) NULL
, [NumeroControlDocumento] nvarchar(20) NULL
, [MontoDocumento] float NULL
, [BaseImponible] float NULL
, [MontoIvaRetenido] float NULL
, [NumeroDocumentoAfectado] nvarchar(20) NULL
, [NumeroComprobante] nvarchar(14) NULL
, [MontoExentoIva] float NULL
, [Alicuota] float NULL
, [NumeroExpediente] nvarchar(15) NULL
, [MontoIva] float NULL
, [FechaComprobante] datetime NULL
, [Periodo] nvarchar(100) NULL
, [PorcentajeRetencion] float NULL
, [NotaCredito] nvarchar(20) NULL
, [NotaDebito] nvarchar(20) NULL
, [Sustraendo] float NULL